// Builds the DTCG token source into:
//   - src/__generated__/theme.light.ts / theme.dark.ts  (antd ThemeConfig)
//   - src/__generated__/tokens.ts                        (flat token map)
//   - dist/brand.css                                     (CSS custom properties)
//
// The DTCG `.tokens.json` files under tokens/ are the single source of truth.
// Run via `pnpm build:tokens` (part of `pnpm build`).
import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const GEN = join(root, 'src', '__generated__');
const DIST = join(root, 'dist');
const ANTD_EXT = 'com.plataforma.antd';

mkdirSync(GEN, { recursive: true });
mkdirSync(DIST, { recursive: true });

/** Resolved value of a DTCG token (arrays — e.g. fontFamily — joined for CSS/antd). */
const valueOf = (t) => {
  const v = t.$value ?? t.value;
  return Array.isArray(v) ? v.join(', ') : v;
};
const antdOf = (t) => t.$extensions?.[ANTD_EXT] ?? t.original?.$extensions?.[ANTD_EXT];

/** Tokens whose CSS var should carry a `px` unit. */
const needsPx = (path) =>
  path[0] === 'space' ||
  path[0] === 'radius' ||
  (path[0] === 'font' && path[1] === 'size');

StyleDictionary.registerFormat({
  name: 'antd/theme-config',
  format: ({ dictionary, options }) => {
    const mode = options.mode === 'dark' ? 'dark' : 'light';
    const token = {};
    const components = {};
    for (const t of dictionary.allTokens) {
      const ext = antdOf(t);
      if (!ext) continue;
      const value = valueOf(t);
      if (ext.component) {
        (components[ext.component] ??= {})[ext.token] = value;
      } else if (ext.token) {
        token[ext.token] = value;
      }
    }
    const algorithm = mode === 'dark' ? 'theme.darkAlgorithm' : 'theme.defaultAlgorithm';
    const indent = (s) => s.replace(/\n/g, '\n  ');
    return [
      `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.`,
      `import { theme, type ThemeConfig } from 'antd';`,
      ``,
      `export const ${mode}Theme: ThemeConfig = {`,
      `  token: ${indent(JSON.stringify(token, null, 2))},`,
      `  components: ${indent(JSON.stringify(components, null, 2))},`,
      `  algorithm: ${algorithm},`,
      `};`,
      ``,
      `export default ${mode}Theme;`,
      ``,
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'ts/flat-tokens',
  format: ({ dictionary }) => {
    const obj = {};
    for (const t of dictionary.allTokens) obj[t.path.join('.')] = valueOf(t);
    return [
      `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.`,
      `export const tokens = ${JSON.stringify(obj, null, 2)} as const;`,
      ``,
      `export type TokenName = keyof typeof tokens;`,
      ``,
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/brand-vars',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const lines = dictionary.allTokens.map((t) => {
      let v = valueOf(t);
      if (typeof v === 'number' && needsPx(t.path)) v = `${v}px`;
      return `  --brand-${t.path.join('-')}: ${v};`;
    });
    return `${selector} {\n${lines.join('\n')}\n}\n`;
  },
});

const baseGlob = join(root, 'tokens/base/*.tokens.json');

async function buildMode(mode, extraFiles = []) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: [baseGlob, join(root, `tokens/modes/${mode}.tokens.json`)],
    platforms: {
      out: {
        buildPath: 'src/__generated__/',
        files: [
          { destination: `theme.${mode}.ts`, format: 'antd/theme-config', options: { mode } },
          ...extraFiles,
        ],
      },
    },
    log: { verbosity: 'silent' },
  });
  await sd.buildAllPlatforms();
}

// Light build also emits the flat token map + the light CSS block.
await buildMode('light', [
  { destination: 'tokens.ts', format: 'ts/flat-tokens' },
  { destination: '_brand.light.css', format: 'css/brand-vars', options: { selector: ':root' } },
]);
// Dark build emits the dark CSS block.
await buildMode('dark', [
  {
    destination: '_brand.dark.css',
    format: 'css/brand-vars',
    options: { selector: '[data-theme="dark"]' },
  },
]);

// Concatenate the two CSS blocks into the published dist/brand.css.
const lightCss = readFileSync(join(GEN, '_brand.light.css'), 'utf8');
const darkCss = readFileSync(join(GEN, '_brand.dark.css'), 'utf8');
writeFileSync(
  join(DIST, 'brand.css'),
  `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand. */\n${lightCss}\n${darkCss}`,
);
rmSync(join(GEN, '_brand.light.css'), { force: true });
rmSync(join(GEN, '_brand.dark.css'), { force: true });

// Sanity: fail the build if the primary seed didn't reach the theme.
if (!readFileSync(join(GEN, 'theme.light.ts'), 'utf8').includes('colorPrimary')) {
  throw new Error('Token build failed: colorPrimary missing from theme.light.ts');
}

console.log('brand-tokens: built theme.light.ts, theme.dark.ts, tokens.ts, dist/brand.css');
