// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
import { theme, type ThemeConfig } from 'antd';

export const darkTheme: ThemeConfig = {
  token: {
    "colorPrimary": "#0066CC",
    "colorSuccess": "#16A34A",
    "colorWarning": "#D97706",
    "colorError": "#DC2626",
    "colorInfo": "#0066CC",
    "motionDurationFast": "0.1s",
    "motionDurationMid": "0.2s",
    "motionDurationSlow": "0.3s",
    "borderRadius": 6,
    "fontFamily": "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif",
    "fontFamilyCode": "SFMono-Regular, Menlo, Consolas, Liberation Mono, monospace",
    "fontSize": 14,
    "fontSizeLG": 16,
    "lineHeight": 1.5715,
    "colorBgBase": "#141414",
    "colorTextBase": "#FFFFFF"
  },
  components: {
    "Button": {
      "controlHeight": 40,
      "fontWeight": 500
    },
    "Card": {
      "borderRadiusLG": 8
    }
  },
  algorithm: theme.darkAlgorithm,
};

export default darkTheme;
